name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-python:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest numpy
    
    - name: Build PyO3 extension
      run: |
        maturin build --release
        pip install target/wheels/*.whl
    
    - name: Run Python tests
      run: python -m pytest tests/ -v --tb=short
  
  test-r:
    name: R Tests  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('reticulate', 'testthat'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin numpy
    
    - name: Build PyO3 extension
      run: |
        maturin build --release
        pip install target/wheels/*.whl
    
    - name: Run R tests
      run: Rscript tests/testthat.R

  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: [test-python]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Rust  
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin pytest pytest-cov numpy
    
    - name: Build PyO3 extension
      run: |
        maturin build --release
        pip install target/wheels/*.whl
    
    - name: Run tests with coverage
      run: python -m pytest tests/ --cov=pybevy --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella